/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.106
 * Generated at: 2020-11-21 01:17:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"copyright\" content=\"All Rights Reserved, Copyright (C) 2013, Wuyeguo, Ltd.\" />\r\n");
      out.write("<title>后台管理主页</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/admin/easyui/easyui/1.3.4/themes/default/easyui.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/admin/easyui/css/wu.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/admin/easyui/css/icon.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/admin/easyui/js/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/admin/easyui/easyui/1.3.4/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/admin/easyui/easyui/1.3.4/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<!-- begin of header -->\r\n");
      out.write("\t<div class=\"wu-header\" data-options=\"region:'north',border:false,split:true\">\r\n");
      out.write("    \t<div class=\"wu-header-left\">\r\n");
      out.write("        \t<h1>资产管理系统</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"wu-header-right\">\r\n");
      out.write("        \t<p><strong class=\"easyui-tooltip\" title=\"2条未读消息\">admin</strong>，欢迎您！</p>\r\n");
      out.write("            <p><a href=\"#\">网站首页</a>|<a href=\"#\">支持论坛</a>|<a href=\"#\">帮助中心</a>|<a href=\"#\">安全退出</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end of header -->\r\n");
      out.write("    <!-- begin of sidebar -->\r\n");
      out.write("\t<div class=\"wu-sidebar\" data-options=\"region:'west',split:true,border:true,title:'导航菜单'\"> \r\n");
      out.write("    \t<div class=\"easyui-accordion\" data-options=\"border:false,fit:true\"> \r\n");
      out.write("        \t<div title=\"快捷菜单\" data-options=\"iconCls:'icon-application-cascade'\" style=\"padding:5px;\">  \t\r\n");
      out.write("    \t\t\t<ul class=\"easyui-tree wu-side-tree\">\r\n");
      out.write("                \t<li iconCls=\"icon-chart-organisation\"><a href=\"javascript:void(0)\" data-icon=\"icon-chart-organisation\" data-link=\"temp/layout-2.html\" iframe=\"0\">菜单导航</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-users\"><a href=\"javascript:void(0)\" data-icon=\"icon-users\" data-link=\"temp/layout-3.html\" iframe=\"0\">用户管理</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-user-group\"><a href=\"javascript:void(0)\" data-icon=\"icon-user-group\" data-link=\"temp/layout-3.html\" iframe=\"0\">角色管理</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-book\"><a href=\"javascript:void(0)\" data-icon=\"icon-book\" data-link=\"temp/layout-3.html\" iframe=\"0\">数据字典</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-cog\"><a href=\"javascript:void(0)\" data-icon=\"icon-cog\" data-link=\"temp/layout-3.html\" iframe=\"0\">系统参数</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-application-osx-error\"><a href=\"javascript:void(0)\" data-icon=\"icon-application-osx-error\" data-link=\"temp/layout-3.html\" iframe=\"0\">操作日志</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div title=\"内容管理\" data-options=\"iconCls:'icon-application-form-edit'\" style=\"padding:5px;\">  \t\r\n");
      out.write("    \t\t\t<ul class=\"easyui-tree wu-side-tree\">\r\n");
      out.write("                \t<li iconCls=\"icon-chart-organisation\"><a href=\"javascript:void(0)\" data-icon=\"icon-chart-organisation\" data-link=\"layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-users\"><a href=\"javascript:void(0)\" data-icon=\"icon-users\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-user-group\"><a href=\"javascript:void(0)\" data-icon=\"icon-user-group\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-book\"><a href=\"javascript:void(0)\" data-icon=\"icon-book\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-cog\"><a href=\"javascript:void(0)\" data-icon=\"icon-cog\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-application-osx-error\"><a href=\"javascript:void(0)\" data-icon=\"icon-application-osx-error\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div title=\"商品管理\" data-options=\"iconCls:'icon-creditcards'\" style=\"padding:5px;\">  \t\r\n");
      out.write("    \t\t\t<ul class=\"easyui-tree wu-side-tree\">\r\n");
      out.write("                \t<li iconCls=\"icon-chart-organisation\"><a href=\"javascript:void(0)\" data-icon=\"icon-chart-organisation\" data-link=\"layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-users\"><a href=\"javascript:void(0)\" data-icon=\"icon-users\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-user-group\"><a href=\"javascript:void(0)\" data-icon=\"icon-user-group\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-book\"><a href=\"javascript:void(0)\" data-icon=\"icon-book\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-cog\"><a href=\"javascript:void(0)\" data-icon=\"icon-cog\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-application-osx-error\"><a href=\"javascript:void(0)\" data-icon=\"icon-application-osx-error\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div title=\"订单管理\" data-options=\"iconCls:'icon-cart'\" style=\"padding:5px;\">  \t\r\n");
      out.write("    \t\t\t<ul class=\"easyui-tree wu-side-tree\">\r\n");
      out.write("                \t<li iconCls=\"icon-chart-organisation\"><a href=\"javascript:void(0)\" data-icon=\"icon-chart-organisation\" data-link=\"layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-users\"><a href=\"javascript:void(0)\" data-icon=\"icon-users\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-user-group\"><a href=\"javascript:void(0)\" data-icon=\"icon-user-group\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-book\"><a href=\"javascript:void(0)\" data-icon=\"icon-book\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-cog\"><a href=\"javascript:void(0)\" data-icon=\"icon-cog\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-application-osx-error\"><a href=\"javascript:void(0)\" data-icon=\"icon-application-osx-error\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div title=\"广告管理\" data-options=\"iconCls:'icon-bricks'\" style=\"padding:5px;\">  \t\r\n");
      out.write("    \t\t\t<ul class=\"easyui-tree wu-side-tree\">\r\n");
      out.write("                \t<li iconCls=\"icon-chart-organisation\"><a href=\"javascript:void(0)\" data-icon=\"icon-chart-organisation\" data-link=\"layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-users\"><a href=\"javascript:void(0)\" data-icon=\"icon-users\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-user-group\"><a href=\"javascript:void(0)\" data-icon=\"icon-user-group\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-book\"><a href=\"javascript:void(0)\" data-icon=\"icon-book\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-cog\"><a href=\"javascript:void(0)\" data-icon=\"icon-cog\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-application-osx-error\"><a href=\"javascript:void(0)\" data-icon=\"icon-application-osx-error\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div title=\"报表中心\" data-options=\"iconCls:'icon-chart-curve'\" style=\"padding:5px;\">  \t\r\n");
      out.write("    \t\t\t<ul class=\"easyui-tree wu-side-tree\">\r\n");
      out.write("                \t<li iconCls=\"icon-chart-organisation\"><a href=\"javascript:void(0)\" data-icon=\"icon-chart-organisation\" data-link=\"layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-users\"><a href=\"javascript:void(0)\" data-icon=\"icon-users\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-user-group\"><a href=\"javascript:void(0)\" data-icon=\"icon-user-group\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-book\"><a href=\"javascript:void(0)\" data-icon=\"icon-book\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-cog\"><a href=\"javascript:void(0)\" data-icon=\"icon-cog\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                    <li iconCls=\"icon-application-osx-error\"><a href=\"javascript:void(0)\" data-icon=\"icon-application-osx-error\" data-link=\"temp/layout-3.html\" iframe=\"0\">导航标题</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div title=\"系统设置\" data-options=\"iconCls:'icon-wrench'\" style=\"padding:5px;\">  \t\r\n");
      out.write("    \t\t\t<ul class=\"easyui-tree wu-side-tree\">\r\n");
      out.write("                \t<li iconCls=\"icon-chart-organisation\"><a href=\"javascript:void(0)\" data-icon=\"icon-chart-organisation\" data-link=\"../admin/menu/list\" iframe=\"0\">菜单管理</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\t\r\n");
      out.write("    <!-- end of sidebar -->    \r\n");
      out.write("    <!-- begin of main -->\r\n");
      out.write("    <div class=\"wu-main\" data-options=\"region:'center'\">\r\n");
      out.write("        <div id=\"wu-tabs\" class=\"easyui-tabs\" data-options=\"border:false,fit:true\">  \r\n");
      out.write("            <div title=\"首页\" data-options=\"href:'welcome',closable:false,iconCls:'icon-tip',cls:'pd3'\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end of main --> \r\n");
      out.write("    <!-- begin of footer -->\r\n");
      out.write("\t<div class=\"wu-footer\" data-options=\"region:'south',border:true,split:true\">\r\n");
      out.write("    \t&copy; 2020 YZU\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end of footer -->  \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$('.wu-side-tree a').bind(\"click\",function(){\r\n");
      out.write("\t\t\t\tvar title = $(this).text();\r\n");
      out.write("\t\t\t\tvar url = $(this).attr('data-link');\r\n");
      out.write("\t\t\t\tvar iconCls = $(this).attr('data-icon');\r\n");
      out.write("\t\t\t\tvar iframe = $(this).attr('iframe')==1?true:false;\r\n");
      out.write("\t\t\t\taddTab(title,url,iconCls,iframe);\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t* Name 载入树形菜单 \r\n");
      out.write("\t\t*/\r\n");
      out.write("\t\t$('#wu-side-tree').tree({\r\n");
      out.write("\t\t\turl:'temp/menu.php',\r\n");
      out.write("\t\t\tcache:false,\r\n");
      out.write("\t\t\tonClick:function(node){\r\n");
      out.write("\t\t\t\tvar url = node.attributes['url'];\r\n");
      out.write("\t\t\t\tif(url==null || url == \"\"){\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\taddTab(node.text, url, '', node.attributes['iframe']);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t* Name 选项卡初始化\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t\t$('#wu-tabs').tabs({\r\n");
      out.write("\t\t\ttools:[{\r\n");
      out.write("\t\t\t\ticonCls:'icon-reload',\r\n");
      out.write("\t\t\t\tborder:false,\r\n");
      out.write("\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t$('#wu-datagrid').datagrid('reload');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}]\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t* Name 添加菜单选项\r\n");
      out.write("\t\t* Param title 名称\r\n");
      out.write("\t\t* Param href 链接\r\n");
      out.write("\t\t* Param iconCls 图标样式\r\n");
      out.write("\t\t* Param iframe 链接跳转方式（true为iframe，false为href）\r\n");
      out.write("\t\t*/\t\r\n");
      out.write("\t\tfunction addTab(title, href, iconCls, iframe){\r\n");
      out.write("\t\t\tvar tabPanel = $('#wu-tabs');\r\n");
      out.write("\t\t\tif(!tabPanel.tabs('exists',title)){\r\n");
      out.write("\t\t\t\tvar content = '<iframe scrolling=\"auto\" frameborder=\"0\"  src=\"'+ href +'\" style=\"width:100%;height:100%;\"></iframe>';\r\n");
      out.write("\t\t\t\tif(iframe){\r\n");
      out.write("\t\t\t\t\ttabPanel.tabs('add',{\r\n");
      out.write("\t\t\t\t\t\ttitle:title,\r\n");
      out.write("\t\t\t\t\t\tcontent:content,\r\n");
      out.write("\t\t\t\t\t\ticonCls:iconCls,\r\n");
      out.write("\t\t\t\t\t\tfit:true,\r\n");
      out.write("\t\t\t\t\t\tcls:'pd3',\r\n");
      out.write("\t\t\t\t\t\tclosable:true\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\ttabPanel.tabs('add',{\r\n");
      out.write("\t\t\t\t\t\ttitle:title,\r\n");
      out.write("\t\t\t\t\t\thref:href,\r\n");
      out.write("\t\t\t\t\t\ticonCls:iconCls,\r\n");
      out.write("\t\t\t\t\t\tfit:true,\r\n");
      out.write("\t\t\t\t\t\tcls:'pd3',\r\n");
      out.write("\t\t\t\t\t\tclosable:true\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ttabPanel.tabs('select',title);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t* Name 移除菜单选项\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t\tfunction removeTab(){\r\n");
      out.write("\t\t\tvar tabPanel = $('#wu-tabs');\r\n");
      out.write("\t\t\tvar tab = tabPanel.tabs('getSelected');\r\n");
      out.write("\t\t\tif (tab){\r\n");
      out.write("\t\t\t\tvar index = tabPanel.tabs('getTabIndex', tab);\r\n");
      out.write("\t\t\t\ttabPanel.tabs('close', index);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
